### ISSUE TITLE
[RFE]Is it possible to support upgrade from the M installation

### ISSUE THREAD

**Issue by myf5** [tigerlinux/openstack-newton-installer-centos7#1]
Hi,
Yours installation script is really useful. I had installed M follow your script. Is it possible to write a script to upgrade M to a higher version like N?  While keep my M settings? Thanks.

**Comment by tigerlinux** [comment]
It could be possible, but for now is out of my scope for this project. Sadly, I'm currently alone on the project and I could need more resources (servers and people) in order to commit to the installer "upgrade mode".
One of the most complex things on OpenStack is precisely the upgrades from version to version.
